//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by myicq.rc
//
#define IDC_MENU_QUICK_REPLY            5
#define IDC_QUICK_REPLY                 7
#define IDD_MYICQ_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_GROUP_FRIEND                104
#define IDS_GROUP_STRANGER              105
#define IDS_GROUP_BLACKLIST             106
#define IDS_BASICINFO_MUST_FILL         107
#define IDS_PASSWD_MISMATCH             108
#define IDS_PLEASE_WAIT                 110
#define IDS_REG_REGISTERING             111
#define IDS_REG_SUCCESS                 113
#define IDS_REG_FAILED                  114
#define IDS_REG_STATUS_SUCCESS          116
#define IDD_REG_MODE                    116
#define IDS_WRONG_PASSWD                117
#define IDD_REG_BASIC                   117
#define IDD_REG_NETWORK                 118
#define IDS_REMOVEITEM                  118
#define IDD_REG_FINISH                  119
#define IDS_RENAMEITEM                  119
#define IDS_REMOVEGROUP                 120
#define IDS_RENAMEGROUP                 121
#define IDS_MESSAGE_EMPTY               122
#define IDS_VIEW_DETAIL                 123
#define IDS_UIN                         124
#define IDS_NICK                        125
#define IDS_FROM_WHERE                  126
#define IDS_SERVER_RELAY                127
#define IDR_MAINFRAME                   128
#define IDS_CHATMODE_NORMAL             128
#define IDR_OUTBAR                      128
#define IDS_CHATMODE_DIALOG             129
#define IDC_FORBIDDEN                   129
#define IDS_GROUP_NOT_EMPTY             130
#define IDC_HAND                        130
#define IDS_PROMPT_DEL_FRIEND           131
#define IDC_DRAG                        131
#define IDD_LOGIN                       132
#define IDS_PROMPT_REJECT_REASON        132
#define IDS_AUTH_REQUEST                133
#define IDS_AUTH_ACCEPTED               134
#define IDS_AUTH_REJECTED               135
#define IDS_UPDATE                      136
#define IDS_MODIFY                      137
#define IDS_MODIFY_DETAIL               138
#define IDS_OPTION_INVISIBLE            139
#define IDS_OPTION_POPUP_ONLINE         140
#define IDR_STATUS                      140
#define IDS_OPTION_GREETING             141
#define IDS_OPTION_POPUP_OFFLINE        142
#define IDD_SEND_MESSAGE                143
#define IDS_OPTION_IGNORE               143
#define IDD_DETAIL_BASIC                144
#define IDS_INTRO                       144
#define IDS_SHOWONLINE                  145
#define IDR_CONTACT                     146
#define IDS_SHOWALL                     146
#define IDS_SEND_RETRY                  147
#define IDS_SORRY                       148
#define IDI_FIND                        149
#define IDS_DEL_FRIEND                  149
#define IDD_SEARCH_MODE                 150
#define IDS_TIMEOUT                     150
#define IDS_FINISHED                    151
#define IDS_FAILED                      152
#define IDI_SYSMSG                      153
#define IDS_REQUEST_SENT                153
#define IDS_ADD_REJECTED                154
#define IDS_ADD_ACCEPTED                155
#define IDR_MAIN                        156
#define IDS_AUTH_REQUIRED               156
#define IDC_PROXY_HOST                  156
#define IDS_TIMEOUT_RETRY               157
#define IDD_OPTION_NETWORK              158
#define IDS_SYS_OPTION                  158
#define IDS_DATE                        159
#define IDS_TIME                        160
#define IDS_CONTENT                     161
#define IDB_STATUS_INVIS                161
#define IDS_SELECT_CONTACT              162
#define IDS_SELECT_RECORD               163
#define IDB_STATUS_ONLINE               163
#define IDC_PROXY_PORT                  163
#define IDS_PROMPT_DEL_SYSMSG           164
#define IDB_STATUS_OFFLINE              164
#define IDS_WARNING                     165
#define IDB_STATUS_AWAY                 165
#define IDS_QUICK_REPLY_SETTING         166
#define IDB_SEND_MSG                    166
#define IDS_MSG_ADDED                   167
#define IDB_RENAME                      167
#define IDS_ADD_FRIEND_REQ              168
#define IDB_SYS_OPTION                  168
#define IDS_AUTOREPLY_1                 169
#define IDB_SHOWONLINE                  169
#define IDS_AUTOREPLY_2                 170
#define IDB_VIEW_DETAIL                 170
#define IDS_AUTOREPLY_3                 171
#define IDB_ADDGROUP                    171
#define IDS_QUICKREPLY_1                172
#define IDB_REG_WIZARD                  172
#define IDS_QUICKREPLY_2                173
#define IDB_CHANGE_USER                 173
#define IDS_QUICKREPLY_3                174
#define IDB_LARGEICON                   174
#define IDI_TIP                         174
#define IDS_QUICKREPLY_4                175
#define IDB_SMALLICON                   175
#define IDI_NETWORK                     175
#define IDS_ERROR_DEL_HOST              176
#define IDB_REMOVEITEM                  176
#define IDI_SENDMSG                     176
#define IDS_INVALID_UIN                 177
#define IDB_BACKGROUND                  177
#define IDB_FONTCOLOR                   178
#define IDS_SYSMSG                      178
#define IDD_ABOUT                       178
#define IDB_HOMEPAGE                    179
#define IDS_SEARCH                      179
#define IDB_EXIT                        180
#define IDS_MAINMENU                    180
#define IDI_STAT                        180
#define IDB_REMOVEGROUP                 181
#define IDS_CHANGE_STATUS               181
#define IDI_ABOUT                       181
#define IDB_MSG_HISTORY                 182
#define IDS_SUCCESS_CONTACTLIST         182
#define IDB_SEARCH                      183
#define IDB_VOICE                       184
#define IDB_CHAT                        185
#define IDS_ACCEPT_REQ                  185
#define IDS_REJECT_REQ                  186
#define IDB_SEND_EMAIL                  187
#define IDI_BLANK                       189
#define IDB_VERT                        191
#define IDB_HELP                        193
#define IDB_CUT                         194
#define IDS_WAITING_REPLY               195
#define IDB_COPY                        195
#define IDB_DEL                         196
#define IDS_PROMPT_VERIFY_PASSWD        197
#define IDR_RECORD                      197
#define IDS_FAILED_HOTKEY               198
#define IDS_NR_ONLINES                  199
#define IDB_ADD                         199
#define IDS_NOTIFY_ONLINE               200
#define IDR_STRANGER                    200
#define IDS_NOTIFY_OFFLINE              201
#define IDR_IGNORE                      201
#define IDS_ERROR                       202
#define IDS_UNKNOWN                     203
#define IDS_STATUS_ONLINE               204
#define IDD_SEARCH_CUSTOM               205
#define IDS_STATUS_OFFLINE              205
#define IDD_SEARCH_RESULT               206
#define IDS_STATUS_AWAY                 206
#define IDS_STATUS_INVIS                207
#define IDS_ABOUT                       208
#define IDS_STATISTICS                  209
#define IDI_FOLDER                      209
#define IDS_SUCCESS_MODIFY_USER         210
#define IDR_MSGMGR_POPUP                210
#define IDS_SUCCESS                     211
#define IDR_MSGVIEW_POPUP               211
#define IDS_STATUS_LOGGING_IN           212
#define IDB_FILEMGR                     212
#define IDD_REG_MISC                    213
#define IDS_ERROR_ADD_YOURSELF          213
#define IDB_CONTACT_MGR                 213
#define IDS_VERIFYING_PASSWD            214
#define IDD_MSG_SEARCH                  214
#define IDS_TITLE_SEARCH_RESULT         215
#define IDS_SEARCH_PAGE_NO              216
#define IDS_SEARCHING_CONTACT           217
#define IDD_VIEW_MESSAGE                218
#define IDS_SEARCH_RESULT_ALL           218
#define IDS_PROXY_SUCCESS               219
#define IDS_PROXY_FAILED                220
#define IDD_OPTION_PLUGIN               223
#define IDI_PLUGIN                      224
#define IDB_CHECK                       225
#define IDB_FOLDER                      226
#define IDD_BROADCAST                   227
#define IDD_OPTION_GENERAL              231
#define IDD_DETAIL_MISC                 236
#define IDD_DETAIL_COMM                 237
#define IDD_SEARCH_ADD                  238
#define IDC_TEXT                        301
#define IDD_SYS_MESSAGE                 309
#define IDD_DETAIL_AUTH                 310
#define IDD_SYS_HISTORY                 426
#define IDC_SENDER                      473
#define IDC_RECEIVER                    476
#define IDD_SEND_REQUEST                478
#define IDC_FACE_SENDER                 483
#define IDD_MSG_VIEW                    485
#define IDC_FACE_RECEIVER               485
#define IDR_MSGMGR                      500
#define IDS_MSG_SENDER                  501
#define IDS_PROMPT_DEL_MSG              502
#define IDS_FILTER_TXT                  503
#define IDS_VIEW_FONT                   504
#define IDS_VIEW_FONTCOLOR              505
#define IDS_MSG_OBJ                     506
#define IDS_GENDER                      507
#define IDS_AGE                         508
#define IDS_COUNTRY                     509
#define IDS_PROVINCE                    510
#define IDS_CITY                        511
#define IDS_EMAIL                       512
#define IDS_ADDRESS                     513
#define IDS_ZIPCODE                     514
#define IDD_LOGIN_AGAIN                 515
#define IDS_TEL                         515
#define IDS_REALNAME                    516
#define IDS_BLOODTYPE                   517
#define IDS_COLLEGE                     518
#define IDS_PROFESSION                  519
#define IDS_HOMEPAGE                    520
#define IDS_SELFINTRO                   521
#define IDS_MALE                        522
#define IDS_FEMALE                      523
#define IDS_OTHERS                      524
#define IDS_FILTER_BAK                  525
#define IDS_LOCATION                    526
#define IDS_HTTP_TEST_SUCCESS           527
#define IDS_HTTP_TEST_FAILED            528
#define IDS_SINGLE_RECIPIENTS           529
#define IDS_MULTIPLE_RECIPIENTS         530
#define IDS_UIN_EMPTY                   531
#define IDS_GROUPSEND_FAILED            532
#define IDS_SKIN_RESTORE                533
#define IDS_PROMPT_DB_CORRUPTED         534
#define IDD_OPTION_SOUND                593
#define IDD_REG_COMM                    684
#define IDD_DEL_FRIEND                  732
#define IDD_OPTION_REPLY                760
#define IDD_DETAIL_CUSTOM               828
#define IDC_UIN                         1000
#define IDC_MAIN_MENU                   1000
#define IDC_PORT                        1001
#define IDC_PASSWD                      1002
#define IDC_SYS_MESSAGE                 1002
#define IDC_STOREPASSWD                 1003
#define IDC_INVISIBLE                   1004
#define IDC_MSG                         1004
#define IDC_PIC                         1006
#define IDC_REGWIZARD                   1007
#define IDC_NICK                        1007
#define IDC_AGE                         1008
#define IDC_GENDER                      1009
#define IDC_TEL                         1017
#define IDC_EDIT1                       1019
#define IDC_ZIPCODE                     1019
#define IDC_HOMEPAGE                    1020
#define IDC_STATIC_PIC                  1022
#define IDC_COLLEGE                     1022
#define IDC_ADDRESS                     1023
#define IDC_ADDR                        1023
#define IDC_COUNTRY                     1024
#define IDC_PROVINCE                    1025
#define IDC_HISTORY                     1026
#define IDC_PROFESSION                  1026
#define IDC_EMAIL                       1028
#define IDC_SEND                        1029
#define IDC_DATE                        1029
#define IDC_SEARCH_RESULT               1030
#define IDC_TIME                        1030
#define IDC_PASSWD_OLD                  1031
#define IDC_ADD_AUTO_REPLY              1031
#define IDC_ADD_QUICK_REPLY             1032
#define IDC_FIND_CONTACT                1034
#define IDC_INTRO                       1035
#define IDC_UPDATE                      1042
#define IDC_SEARCH_DETAIL               1042
#define IDC_SEND_REQUEST                1042
#define IDC_DEL_AUTO_REPLY              1042
#define IDC_DELETE                      1042
#define IDC_DEL_QUICK_REPLY             1043
#define IDC_DELETE_ALL                  1043
#define IDC_EXISTING_UIN                1043
#define IDC_NEW_UIN                     1044
#define IDC_SEARCH_NEXT                 1045
#define IDC_SEARCH_PREV                 1046
#define IDC_PASSWD_AGAIN                1046
#define IDC_MSG_HISTORY                 1046
#define IDC_SEARCH_ALL                  1047
#define IDC_LOWER                       1047
#define IDC_NEXT_MSG                    1048
#define IDC_MSG_VIEW                    1049
#define IDC_SOUND_OFF                   1051
#define IDC_MSG_EDIT                    1052
#define IDC_HOTKEY_CUSTOM               1052
#define IDC_CHATMODE                    1053
#define IDC_UPPER                       1054
#define IDC_CITY                        1056
#define IDC_ENTER                       1057
#define IDC_REMARK                      1057
#define IDC_CTRLENTER                   1058
#define IDC_BLOOD                       1058
#define IDC_NAME                        1059
#define IDC_MODIFY                      1060
#define IDC_SOUND_EVENT                 1061
#define IDC_USER                        1063
#define IDC_STATIC_UIN                  1064
#define IDC_SEARCH_ONLINE               1065
#define IDC_AUTH_ALL                    1065
#define IDC_SOUND_ON                    1065
#define IDC_STATIC_PASSWD               1065
#define IDC_REQUEST                     1066
#define IDC_HOST                        1066
#define IDC_FILE                        1066
#define IDC_SOUND_FILE                  1066
#define IDC_HOTKEY_DEFAULT              1066
#define IDC_TEXT_AUTO_REPLY             1066
#define IDC_SEARCH_CUSTOM               1067
#define IDC_ALWAYS_ON_TOP               1067
#define IDC_TEXT_QUICK_REPLY            1067
#define IDC_AUTH_REQUEST                1068
#define IDC_AUTH_NONE                   1069
#define IDC_TASKBAR_STYLE               1069
#define IDC_MATCH_WHOLE                 1070
#define IDC_POPUP_MSG                   1070
#define IDC_SHOW_ONLINE_ONLY            1071
#define IDC_SEARCH_TEXT                 1071
#define IDC_CONTACT_COMBO               1072
#define IDC_ONLINE_NOTIFY               1073
#define IDC_MODE                        1073
#define IDC_RADIO2                      1074
#define IDC_MONITOR_NETWORK             1075
#define IDC_RADIO3                      1075
#define IDC_COLORFUL_URL                1076
#define IDC_SEARCH                      1076
#define IDC_RESULT                      1077
#define IDC_MODIFY_PASSWD               1078
#define IDC_SEARCH_STATIC               1078
#define IDC_PROXY_TYPE                  1081
#define IDC_STATUS_DETAIL               1082
#define IDC_USE_PROXY                   1082
#define IDC_STATUS                      1083
#define IDC_AUTO_REPLY                  1083
#define IDC_PROXY_USERNAME              1083
#define IDC_ADD_FRIEND                  1084
#define ID_STATISTICS                   1084
#define IDC_PROXY_PASSWD                1084
#define ID_ABOUT                        1085
#define IDC_PROXY_TEST                  1085
#define IDC_PROXY_RESOLVE               1087
#define IDC_AUTO_STATUS_TIME            1088
#define IDC_GROUPSEND                   1090
#define IDC_RECIPIENTS                  1091
#define IDC_GREETING                    1092
#define IDC_RECIPIENTS_STATIC           1092
#define IDC_IPPORT                      1093
#define IDC_CONFIG                      1095
#define IDC_ABOUT                       1096
#define IDC_REQ_REJECT                  1097
#define IDC_PLUGIN_LIST                 1097
#define IDC_REQ_ACCEPT                  1098
#define IDC_NETWORK_TYPE                1098
#define IDC_EXPIRE                      1101
#define IDC_NR_ONLINES                  1123
#define IDC_HOTKEY                      1129
#define IDC_IGNORE_STRANGER             1146
#define IDC_LOGIN_INVIS                 1147
#define IDC_CHOOSER_AUTO_REPLY          1191
#define IDC_CHOOSER_QUICK_REPLY         1192
#define IDC_ACCESS_PUBLIC               1193
#define IDC_SWITCH_STATUS               1193
#define IDC_ACCESS_FRIEND               1194
#define IDC_ACCESS_PRIVATE              1195
#define IDC_DEL_FRIEND                  1199
#define IDC_STATIC_ACCESS               1216
#define IDC_AUTO_CANCEL_AWAY            1228
#define IDC_AUTO_SWITCH_STATUS          1229
#define IDC_USE_HOTKEY                  1260
#define IDC_OPTIONS                     1313
#define IDC_BROWSE                      1314
#define IDC_PLAY                        1316
#define IDC_SOUND                       1317
#define IDC_CUSTOM_SOUND                1327
#define IDC_TASKBAR_ICON                1328
#define ID_GFX_LARGEICON                32771
#define ID_GFX_SMALLICON                32772
#define ID_GFX_ADDGROUP                 32773
#define ID_GFX_FONTCOLOR                32776
#define ID_GFX_BACKGROUND               32777
#define ID_SYS_OPTION                   32780
#define ID_STATUS_ONLINE                32781
#define ID_STATUS_OFFLINE               32782
#define ID_MODIFY_INFO                  32786
#define ID_STATUS_INVIS                 32788
#define ID_STATUS_AWAY_NOREPLY          32791
#define ID_STATUS_AWAY_CUSTOM           32792
#define ID_SEND_MSG                     32793
#define ID_MSG_HISTORY                  32794
#define ID_VIEW_DETAIL                  32795
#define ID_REG_WIZARD                   32796
#define ID_CHANGE_USER                  32797
#define ID_RECORD_COPY                  32798
#define ID_RECORD_CUT                   32799
#define ID_RECORD_DEL                   32800
#define ID_ADD_AS_FRIEND                32801
#define ID_FILE_IMPORT                  32802
#define ID_EXPORT_BACKUP                32803
#define ID_EXPORT_TXT                   32804
#define ID_HOMEPAGE                     32805
#define ID_EXPORT_BAK                   32805
#define ID_SEND_EMAIL                   32806
#define ID_FILE_EXIT                    32808
#define ID_EDIT_SEARCH                  32809
#define ID_EDIT_DEL                     32810
#define ID_VIEW_FONT                    32815
#define ID_VIEW_BGCOLOR                 32816
#define ID_EXPORT_CONTACT               32819
#define ID_CONTACT_MGR                  32820
#define ID_MESSAGE_MGR                  32821
#define ID_BROADCAST_MSG                32823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
