# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# vagrant plugin install vagrant-disksize
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  (0..0).each do |i|
    config.vm.define vm_name = "centos#{i}"  do |config|
        config.vm.provider "virtualbox" do |v|
            v.gui = true
            v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "1536",'--cpus', 2]
        end
        config.vm.box = "centos7-base"
        # config.disksize.size = '16GB'
        config.ssh.forward_agent = true
        config.vm.hostname = vm_name
        config.vm.synced_folder "./test", "/home/vagrant/test", owner: "vagrant"
        config.vm.synced_folder "/Users/alex/test", "/test", owner: "vagrant"
        config.ssh.username = "vagrant"
        # config.ssh.private_key_path = "~/test/vagrant/redis/.ssh/id_rsa"
        config.ssh.password = "vagrant"
        config.vm.network :private_network, ip: "192.168.11.10#{i}"
        config.vm.boot_timeout = 60
        config.vm.provision :shell, :path => "bootstrap.sh"
    end
  end
end



