//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Client.rc
//
#define ID_NEXT                         3
#define ID_SHOW_TALK                    4
#define ID_USER_REGISTR                 5
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_CLIENTTYPE                  129
#define IDB_IMAGELIST                   129
#define IDD_SEVER_SETUP                 130
#define IDC_DRAGGING                    131
#define IDB_SMALL_IMAGELIST             131
#define IDD_REGISTER                    131
#define IDC_NODRAGGING                  132
#define IDI_CHECK_LARGE                 133
#define IDC_HANDCUR                     136
#define IDI_CHECK_SMALL                 136
#define IDR_TOOLBAR1                    138
#define IDR_QQ                          140
#define IDR_TOOLBAR2                    140
#define IDR_TRAYICON                    142
#define IDI_RED                         144
#define IDI_CHECK_LARGE1                145
#define IDR_POPMENU                     145
#define IDR_TOOLBAR3                    146
#define IDD_MULTI_SEND                  148
#define IDD_SENDTO_ALL                  149
#define IDD_SEND_BROADCAST              150
#define IDI_ICON1                       154
#define IDD_DIALOG1                     156
#define IDD_DIALOG2                     158
#define IDD_DIALOG3                     159
#define IDD_DIALOG4                     160
#define IDD_LOOK_MESS                   218
#define IDD_LOGIN                       225
#define IDD_SYSPARA                     231
#define IDD_BASE_1DLG                   235
#define IDR_MESSAGE1                    282
#define IDR_MESSAGE                     291
#define IDR_SEARCH                      303
#define IDD_SHOW_ADD_FRIEND             309
#define IDD_SEND_MESS                   313
#define ID_CHANGE_PWD                   314
#define IDD_FRIEND_DETAIL               315
#define IDD_MYSELF_DETAIL               316
#define IDB_FIND                        377
#define IDR_NOTIFY                      387
#define IDR_CHAT                        427
#define IDB_PERSON_SETUP                466
#define IDB_QUIT                        471
#define IDB_HELP                        476
#define IDB_SYS_SETUP                   498
#define IDB_MESSAGE                     502
#define IDR_ONHIDE                      562
#define IDR_HOMEPAGE                    647
#define IDB_MESS_MANAGE                 650
#define IDR_FRIEND                      662
#define IDB_FIND1                       721
#define IDB_FIND2                       731
#define IDD_SHOWBROADCAST               733
#define IDD_SHOWBROADCAST11             734
#define IDD_SEARCH                      735
#define IDD_SHOW_ONLINE                 736
#define IDD_ADD_FRIEND                  737
#define IDR_DOWN                        741
#define IDR_MDISABLE                    742
#define IDR_OFFLINE                     742
#define IDR_FIND                        743
#define IDR_ONLINE                      745
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_RADIO1                      1002
#define IDC_APPLY_ID                    1002
#define IDC_RADIO2                      1003
#define IDC_USE_HAVEID                  1003
#define ID_UID_LIST                     1004
#define IDC_EDIT3                       1004
#define IDC_USER_ID                     1004
#define IDC_TALK                        1004
#define IDC_MSG                         1004
#define IDC_EDITID                      1004
#define IDC_EDIT4                       1005
#define IDC_USER_PWD                    1005
#define IDC_PICTURE                     1005
#define IDC_COMBO1                      1006
#define IDC_HEADBMP                     1006
#define IDC_EDIT5                       1007
#define IDC_NAME                        1007
#define IDC_EDIT6                       1008
#define IDC_AGE                         1008
#define IDC_EDIT7                       1009
#define IDC_DESCRIPTION                 1009
#define IDC_EDIT8                       1010
#define IDC_PWD                         1010
#define IDC_EDIT9                       1011
#define IDC_PWD1                        1011
#define ID_REFRESH                      1011
#define ID_USER_PWD                     1012
#define IDC_COMBO2                      1012
#define IDC_SEX                         1012
#define IDC_EDIT10                      1013
#define IDC_PHONE                       1013
#define IDC_EDIT11                      1014
#define IDC_FAX                         1014
#define IDC_EDIT12                      1015
#define IDC_ADDRESS                     1015
#define IDC_EDIT13                      1016
#define IDC_DEPARTMENT                  1016
#define IDC_EDIT14                      1017
#define IDC_HOMEPAGE                    1017
#define IDC_EDIT15                      1018
#define IDC_EMAIL                       1018
#define IDC_SERVERIP                    1019
#define IDC_SERVER_PORT                 1020
#define ID_SHOW_CHANGEPWD               1024
#define ID_SHOW_HISTORY                 1026
#define IDC_ID                          1028
#define IDC_LIST1                       1028
#define IDC_DATE                        1029
#define IDC_RADIO_ID                    1029
#define IDC_TIME                        1030
#define IDC_RADIO_NAME                  1030
#define IDC_BYID                        1031
#define IDC_OLDPWD                      1031
#define IDC_BYNAME                      1032
#define IDC_NEXTPAGE                    1033
#define IDC_NEW_PWD1                    1033
#define IDC_LASTPAGE                    1034
#define IDC_NEW_PWD2                    1034
#define IDC_EDITNAME                    1035
#define IDC_NEXTPAGE2                   1035
#define IDC_REFRESH                     1035
#define IDC_EDITMSG                     1036
#define IDC_HISTORY                     1039
#define ID_MODIFYPI                     1040
#define ID_SHOW_DETAIL                  1042
#define IDC_SHOW_DETAIL                 1042
#define IDC_FRIEND_DETAIL               1042
#define IDC_RECT                        1044
#define IDC_TALK_RECORD                 1046
#define ID_ONHIDE_LOGIN                 1061
#define IDC_ALLOW_ALL                   1065
#define IDC_SEND_MSG                    1066
#define IDC_NEED_CHECK                  1068
#define IDC_NOT_ALLOW                   1069
#define IDC_START_CHANG                 1078
#define ID_ADD_AS_FRIEND                1084
#define ID_SEND_REQUEST                 1096
#define ID_REFUSE                       1097
#define ID_AGREE                        1098
#define ID_MESSAGE_MANAGE               32771
#define ID_MENUITEM32772                32772
#define IDM_SHOW                        32773
#define ID_SENDTO_ALL                   32774
#define IDM_ONLINE                      32775
#define ID_MULTISEND                    32775
#define ID_SEND_BYNAME                  32776
#define IDM_OFFLINE                     32776
#define ID_SYS_SETUP                    32777
#define ID_PERSONINFO_SETUP             32778
#define ID_EXIT                         32778
#define ID_ONLINE                       32779
#define ID_ONHIDE                       32780
#define ID_OFFLINE                      32781
#define ID_SEARCH                       32786
#define ID_SEND_BROADCAST               32787
#define ID_SEND_MESSAGE                 32802
#define ID_SEND_FILE                    32803
#define ID_FRIEND_DETAIL                32804
#define ID_PERSON_HOMEPAGE              32805
#define ID_SEND_EMAIL                   32806
#define ID_CUR_CHATRECORD               32819
#define ID_ADD_FRIEND                   32820
#define ID_FRIENDS_DETAIL               32821
#define ID_SHOW_ONLINE                  32822
#define ID_GFX_SMALLICON                50000
#define ID_GFX_LARGEICON                50001
#define ID_GFX_REMOVEITEM               50002
#define ID_GFX_RENAMEITEM               50003
#define ID_GFX_GROUPICON                50004
#define ID_GFX_FONTCICON                50005
#define ID_GFX_BACKCICON                50006
#define IDS_NOT_LOGIN_SERVER            61204
#define IDS_ASK_RETRY                   61205
#define IDS_CANNOT_SEND_NULL            61206
#define IDS_PWD_ERROR                   61207
#define IDS_ASK_CHECK_PWD_ONSERVER      61208
#define IDS_SERVER_NOT_RES              61209
#define IDS_SERVER_IP_NOT_NULL          61210
#define IDS_FILL_PWD_ERROR              61211
#define IDS_FILL_ID_ERROR               61212
#define IDS_PWD_NOT_NULL                61213
#define IDS_ID_NOT_EXIST                61215
#define IDS_NOT_FINISH                  61216
#define IDS_HOTKEY_REG_FAIL             61217
#define IDS_CREATE_USERFILE_FAIL        61218
#define IDS_FACE_FILE_LOAD_FAILE        61219
#define IDS_CREATE_SOCKET_ERROR         61220
#define IDS_SETUP_NOTICE                61221

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
