# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  (0..0).each do |i|
    config.vm.define vm_name = "node#{i}"  do |config|
        config.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "3072",'--cpus', 2]
        end
        config.vm.box = "dev"
		config.disksize.size = '22GB'
        config.vm.hostname = vm_name
        config.ssh.username = "vagrant"
        config.vm.network :private_network, ip: "192.168.100.10#{i}"
	  	config.vm.provision :shell, :path => "bootstrap.sh"
    end
  end
end



