// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tellist.proto

#ifndef PROTOBUF_tellist_2eproto__INCLUDED
#define PROTOBUF_tellist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace baidu {
namespace hi {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_tellist_2eproto();
void protobuf_AssignDesc_tellist_2eproto();
void protobuf_ShutdownFile_tellist_2eproto();

class hi_tel_num_list;

// ===================================================================

class hi_tel_num_list : public ::google::protobuf::Message {
 public:
  hi_tel_num_list();
  virtual ~hi_tel_num_list();

  hi_tel_num_list(const hi_tel_num_list& from);

  inline hi_tel_num_list& operator=(const hi_tel_num_list& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const hi_tel_num_list& default_instance();

  void Swap(hi_tel_num_list* other);

  // implements Message ----------------------------------------------

  hi_tel_num_list* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const hi_tel_num_list& from);
  void MergeFrom(const hi_tel_num_list& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 tel_num = 1;
  inline int tel_num_size() const;
  inline void clear_tel_num();
  static const int kTelNumFieldNumber = 1;
  inline ::google::protobuf::uint64 tel_num(int index) const;
  inline void set_tel_num(int index, ::google::protobuf::uint64 value);
  inline void add_tel_num(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      tel_num() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_tel_num();

  // @@protoc_insertion_point(class_scope:baidu.hi.hi_tel_num_list)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > tel_num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_tellist_2eproto();
  friend void protobuf_AssignDesc_tellist_2eproto();
  friend void protobuf_ShutdownFile_tellist_2eproto();

  void InitAsDefaultInstance();
  static hi_tel_num_list* default_instance_;
};
// ===================================================================


// ===================================================================

// hi_tel_num_list

// repeated uint64 tel_num = 1;
inline int hi_tel_num_list::tel_num_size() const {
  return tel_num_.size();
}
inline void hi_tel_num_list::clear_tel_num() {
  tel_num_.Clear();
}
inline ::google::protobuf::uint64 hi_tel_num_list::tel_num(int index) const {
  return tel_num_.Get(index);
}
inline void hi_tel_num_list::set_tel_num(int index, ::google::protobuf::uint64 value) {
  tel_num_.Set(index, value);
}
inline void hi_tel_num_list::add_tel_num(::google::protobuf::uint64 value) {
  tel_num_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
hi_tel_num_list::tel_num() const {
  return tel_num_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
hi_tel_num_list::mutable_tel_num() {
  return &tel_num_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hi
}  // namespace baidu

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tellist_2eproto__INCLUDED
