# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# vagrant plugin install vagrant-disksize
# vagrant plugin install vagrant-persistent-storage
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  (0..0).each do |i|
    config.vm.define vm_name = "node#{i}"  do |config|
        config.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "3072",'--cpus', 2]
        end
        config.vm.box = "cdh"
		config.disksize.size = '35GB'
        config.vm.hostname = vm_name
        config.ssh.username = "vagrant"
        config.vm.network :private_network, ip: "192.168.100.10#{i}"
	  	config.vm.provision :shell, :path => "bootstrap.sh"

		config.persistent_storage.enabled = true
		config.persistent_storage.location = "~/tmp/cdh.vdi"
		config.persistent_storage.size = 1024000 # 10G
		config.persistent_storage.mountname = 'cloudera'
		config.persistent_storage.filesystem = 'ext2'
		config.persistent_storage.mountpoint = '/opt/cloudera/'
		config.persistent_storage.volgroupname = 'myvolgroup'
    end
  end
end

