/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_tellist_2eproto_INCLUDED
#define PROTOBUF_C_tellist_2eproto_INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _phone_contact_uin_tel phone_contact_uin_tel;
typedef struct _phone_contact_uin_tel_list phone_contact_uin_tel_list;


/* --- enums --- */


/* --- messages --- */

struct  _phone_contact_uin_tel
{
  ProtobufCMessage base;
  char *name;
  int has_num;
  unsigned long long int num;
};
#define phone_contact_uin_tel_Init \
 { PROTOBUF_C_MESSAGE_INIT (&phone_contact_uin_tel_descriptor) \
    , NULL, 0,0 }


struct  _phone_contact_uin_tel_list
{
  ProtobufCMessage base;
  size_t n_tel;
  phone_contact_uin_tel **tel;
};
#define phone_contact_uin_tel_list_Init \
 { PROTOBUF_C_MESSAGE_INIT (&phone_contact_uin_tel_list_descriptor) \
    , 0,NULL }


/* phone_contact_uin_tel methods */
void   phone_contact_uin_tel_init
                     (phone_contact_uin_tel         *message);
size_t phone_contact_uin_tel_get_packed_size
                     (const phone_contact_uin_tel   *message);
size_t phone_contact_uin_tel_pack
                     (const phone_contact_uin_tel   *message,
                      unsigned char             *out);
size_t phone_contact_uin_tel_pack_to_buffer
                     (const phone_contact_uin_tel   *message,
                      ProtobufCBuffer     *buffer);
phone_contact_uin_tel *
       phone_contact_uin_tel_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const unsigned char       *data);
void   phone_contact_uin_tel_free_unpacked
                     (phone_contact_uin_tel *message,
                      ProtobufCAllocator *allocator);
/* phone_contact_uin_tel_list methods */
void   phone_contact_uin_tel_list_init
                     (phone_contact_uin_tel_list         *message);
size_t phone_contact_uin_tel_list_get_packed_size
                     (const phone_contact_uin_tel_list   *message);
size_t phone_contact_uin_tel_list_pack
                     (const phone_contact_uin_tel_list   *message,
                      unsigned char             *out);
size_t phone_contact_uin_tel_list_pack_to_buffer
                     (const phone_contact_uin_tel_list   *message,
                      ProtobufCBuffer     *buffer);
phone_contact_uin_tel_list *
       phone_contact_uin_tel_list_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const unsigned char       *data);
void   phone_contact_uin_tel_list_free_unpacked
                     (phone_contact_uin_tel_list *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*phone_contact_uin_tel_Closure)
                 (const phone_contact_uin_tel *message,
                  void *closure_data);
typedef void (*phone_contact_uin_tel_list_Closure)
                 (const phone_contact_uin_tel_list *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor phone_contact_uin_tel_descriptor;
extern const ProtobufCMessageDescriptor phone_contact_uin_tel_list_descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_tellist_2eproto_INCLUDED */
