/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "tellist.pc.h"
void   phone_contact_uin_tel_init
                     (phone_contact_uin_tel         *message)
{
  static phone_contact_uin_tel init_value = phone_contact_uin_tel_Init;
  *message = init_value;
}
size_t phone_contact_uin_tel_get_packed_size
                     (const phone_contact_uin_tel *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phone_contact_uin_tel_pack
                     (const phone_contact_uin_tel *message,
                      unsigned char       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phone_contact_uin_tel_pack_to_buffer
                     (const phone_contact_uin_tel *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
phone_contact_uin_tel *
       phone_contact_uin_tel_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const unsigned char       *data)
{
  return (phone_contact_uin_tel *)
     protobuf_c_message_unpack (&phone_contact_uin_tel_descriptor,
                                allocator, len, data);
}
void   phone_contact_uin_tel_free_unpacked
                     (phone_contact_uin_tel *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   phone_contact_uin_tel_list_init
                     (phone_contact_uin_tel_list         *message)
{
  static phone_contact_uin_tel_list init_value = phone_contact_uin_tel_list_Init;
  *message = init_value;
}
size_t phone_contact_uin_tel_list_get_packed_size
                     (const phone_contact_uin_tel_list *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_list_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phone_contact_uin_tel_list_pack
                     (const phone_contact_uin_tel_list *message,
                      unsigned char       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_list_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phone_contact_uin_tel_list_pack_to_buffer
                     (const phone_contact_uin_tel_list *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_list_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
phone_contact_uin_tel_list *
       phone_contact_uin_tel_list_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const unsigned char       *data)
{
  return (phone_contact_uin_tel_list *)
     protobuf_c_message_unpack (&phone_contact_uin_tel_list_descriptor,
                                allocator, len, data);
}
void   phone_contact_uin_tel_list_free_unpacked
                     (phone_contact_uin_tel_list *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &phone_contact_uin_tel_list_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor phone_contact_uin_tel_field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(phone_contact_uin_tel, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(phone_contact_uin_tel, has_num),
    PROTOBUF_C_OFFSETOF(phone_contact_uin_tel, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phone_contact_uin_tel_field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = num */
};
static const ProtobufCIntRange phone_contact_uin_tel_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor phone_contact_uin_tel_descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "phone.contact.uin_tel",
  "UinTel",
  "phone_contact_uin_tel",
  "phone.contact",
  sizeof(phone_contact_uin_tel),
  2,
  phone_contact_uin_tel_field_descriptors,
  phone_contact_uin_tel_field_indices_by_name,
  1,  phone_contact_uin_tel_number_ranges,
  (ProtobufCMessageInit) phone_contact_uin_tel_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor phone_contact_uin_tel_list_field_descriptors[1] =
{
  {
    "tel",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(phone_contact_uin_tel_list, n_tel),
    PROTOBUF_C_OFFSETOF(phone_contact_uin_tel_list, tel),
    &phone_contact_uin_tel_descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phone_contact_uin_tel_list_field_indices_by_name[] = {
  0,   /* field[0] = tel */
};
static const ProtobufCIntRange phone_contact_uin_tel_list_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor phone_contact_uin_tel_list_descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "phone.contact.uin_tel_list",
  "UinTelList",
  "phone_contact_uin_tel_list",
  "phone.contact",
  sizeof(phone_contact_uin_tel_list),
  1,
  phone_contact_uin_tel_list_field_descriptors,
  phone_contact_uin_tel_list_field_indices_by_name,
  1,  phone_contact_uin_tel_list_number_ranges,
  (ProtobufCMessageInit) phone_contact_uin_tel_list_init,
  NULL,NULL,NULL    /* reserved[123] */
};
