// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tellist.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tellist.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace baidu {
namespace hi {

namespace {

const ::google::protobuf::Descriptor* hi_tel_num_list_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  hi_tel_num_list_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_tellist_2eproto() {
  protobuf_AddDesc_tellist_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tellist.proto");
  GOOGLE_CHECK(file != NULL);
  hi_tel_num_list_descriptor_ = file->message_type(0);
  static const int hi_tel_num_list_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hi_tel_num_list, tel_num_),
  };
  hi_tel_num_list_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      hi_tel_num_list_descriptor_,
      hi_tel_num_list::default_instance_,
      hi_tel_num_list_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hi_tel_num_list, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hi_tel_num_list, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(hi_tel_num_list));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tellist_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    hi_tel_num_list_descriptor_, &hi_tel_num_list::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_tellist_2eproto() {
  delete hi_tel_num_list::default_instance_;
  delete hi_tel_num_list_reflection_;
}

void protobuf_AddDesc_tellist_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rtellist.proto\022\010baidu.hi\"\"\n\017hi_tel_num_"
    "list\022\017\n\007tel_num\030\001 \003(\004", 61);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tellist.proto", &protobuf_RegisterTypes);
  hi_tel_num_list::default_instance_ = new hi_tel_num_list();
  hi_tel_num_list::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tellist_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tellist_2eproto {
  StaticDescriptorInitializer_tellist_2eproto() {
    protobuf_AddDesc_tellist_2eproto();
  }
} static_descriptor_initializer_tellist_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int hi_tel_num_list::kTelNumFieldNumber;
#endif  // !_MSC_VER

hi_tel_num_list::hi_tel_num_list()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void hi_tel_num_list::InitAsDefaultInstance() {
}

hi_tel_num_list::hi_tel_num_list(const hi_tel_num_list& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void hi_tel_num_list::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

hi_tel_num_list::~hi_tel_num_list() {
  SharedDtor();
}

void hi_tel_num_list::SharedDtor() {
  if (this != default_instance_) {
  }
}

void hi_tel_num_list::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* hi_tel_num_list::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return hi_tel_num_list_descriptor_;
}

const hi_tel_num_list& hi_tel_num_list::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tellist_2eproto();
  return *default_instance_;
}

hi_tel_num_list* hi_tel_num_list::default_instance_ = NULL;

hi_tel_num_list* hi_tel_num_list::New() const {
  return new hi_tel_num_list;
}

void hi_tel_num_list::Clear() {
  tel_num_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool hi_tel_num_list::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint64 tel_num = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_tel_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 8, input, this->mutable_tel_num())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_tel_num())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_tel_num;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void hi_tel_num_list::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated uint64 tel_num = 1;
  for (int i = 0; i < this->tel_num_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      1, this->tel_num(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* hi_tel_num_list::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated uint64 tel_num = 1;
  for (int i = 0; i < this->tel_num_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(1, this->tel_num(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int hi_tel_num_list::ByteSize() const {
  int total_size = 0;

  // repeated uint64 tel_num = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->tel_num_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->tel_num(i));
    }
    total_size += 1 * this->tel_num_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void hi_tel_num_list::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const hi_tel_num_list* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const hi_tel_num_list*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void hi_tel_num_list::MergeFrom(const hi_tel_num_list& from) {
  GOOGLE_CHECK_NE(&from, this);
  tel_num_.MergeFrom(from.tel_num_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void hi_tel_num_list::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void hi_tel_num_list::CopyFrom(const hi_tel_num_list& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool hi_tel_num_list::IsInitialized() const {

  return true;
}

void hi_tel_num_list::Swap(hi_tel_num_list* other) {
  if (other != this) {
    tel_num_.Swap(&other->tel_num_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata hi_tel_num_list::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = hi_tel_num_list_descriptor_;
  metadata.reflection = hi_tel_num_list_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hi
}  // namespace baidu

// @@protoc_insertion_point(global_scope)
